### ISSUE TITLE
请问这个支持Hygon DCU吗？

### ISSUE THREAD

**Issue by lql341** [ChipSum-Group/ChipSum#6]
当执行 python3 setup.py arch=VEGA906 compiler=/public/software/compiler/rocm/dtk-21.10.1/bin/hipcc hip=/public/software/compiler/rocm/dtk-21.10.1 j=8 报错如下：
![image](https://user-images.githubusercontent.com/35156008/160342357-01f32b8d-a0de-48f2-a2af-a94a65b880f1.png)

测试环境： 超算平台Centos 7.6,  Rocm 4.3, DCU

**Comment by Riiiichman-Li** [comment]
您好，因为一些个人问题和仓库迁移问题，很抱歉没有及时回复。

该项目能够支持Hygon DCU，并且已经在两个DCU集群上成功运行。除此之外，我们还针对Hygon DCU进行了一些性能测试。

我们还在V100和A100，以及AMD Radeon Pro VII上获得了一些不错的性能测试结果。

后续我们会经常check这里的issue，感谢关注。

**Comment by lql341** [comment]
> 您好，因为一些个人问题和仓库迁移问题，很抱歉没有及时回复。
> 
> 该项目能够支持Hygon DCU，并且已经在两个DCU集群上成功运行。除此之外，我们还针对Hygon DCU进行了一些性能测试。
> 
> 我们还在V100和A100，以及AMD Radeon Pro VII上获得了一些不错的性能测试结果。
> 
> 后续我们会经常check这里的issue，感谢关注。如果有任何问题，可通过私信联系我们。

感谢回复，我之前在上面运行的时候，编译Chipsum还是会有报错，是最近加的支持嘛？报错如上。

**Comment by Riiiichman-Li** [comment]
> > 您好，因为一些个人问题和仓库迁移问题，很抱歉没有及时回复。
> > 该项目能够支持Hygon DCU，并且已经在两个DCU集群上成功运行。除此之外，我们还针对Hygon DCU进行了一些性能测试。
> > 我们还在V100和A100，以及AMD Radeon Pro VII上获得了一些不错的性能测试结果。
> > 后续我们会经常check这里的issue，感谢关注。如果有任何问题，可通过私信联系我们。
> 
> 感谢回复，我之前在上面运行的时候，编译Chipsum还是会有报错，是最近加的支持嘛？报错如上。

您的错误可能是由于使用了4.3版本的ROCm套件导致的。据我所知，4.3版本的ROCm套件需要CentOs 7.9或8.3的支持
![Screenshot_20220419_185631_com huawei browser](https://user-images.githubusercontent.com/86460876/163992505-1472e06a-6f02-48ab-82ac-333a21029342.jpg)
我们在更低版本的CentOS上用了4.0版本的ROCm套件。

**Comment by lql341** [comment]
> > > 您好，因为一些个人问题和仓库迁移问题，很抱歉没有及时回复。
> > > 该项目能够支持Hygon DCU，并且已经在两个DCU集群上成功运行。除此之外，我们还针对Hygon DCU进行了一些性能测试。
> > > 我们还在V100和A100，以及AMD Radeon Pro VII上获得了一些不错的性能测试结果。
> > > 后续我们会经常check这里的issue，感谢关注。如果有任何问题，可通过私信联系我们。
> > 
> > 
> > 感谢回复，我之前在上面运行的时候，编译Chipsum还是会有报错，是最近加的支持嘛？报错如上。
> 
> 您的错误可能是由于使用了4.3版本的ROCm套件导致的。据我所知，4.3版本的ROCm套件需要CentOs 7.9或8.3的支持 ![Screenshot_20220419_185631_com huawei browser](https://user-images.githubusercontent.com/86460876/163992505-1472e06a-6f02-48ab-82ac-333a21029342.jpg) 我们在更低版本的CentOS上用了4.0版本的ROCm套件。

我本地环境使用的是Centos 7.6, Rocm是4.3，但是编译kokkos的报错了，可能我需要低版本的kokkos?

**Comment by Riiiichman-Li** [comment]
> > > > 您好，因为一些个人问题和仓库迁移问题，很抱歉没有及时回复。
> > > > 该项目能够支持Hygon DCU，并且已经在两个DCU集群上成功运行。除此之外，我们还针对Hygon DCU进行了一些性能测试。
> > > > 我们还在V100和A100，以及AMD Radeon Pro VII上获得了一些不错的性能测试结果。
> > > > 后续我们会经常check这里的issue，感谢关注。如果有任何问题，可通过私信联系我们。
> > > 
> > > 
> > > 感谢回复，我之前在上面运行的时候，编译Chipsum还是会有报错，是最近加的支持嘛？报错如上。
> > 
> > 
> > 您的错误可能是由于使用了4.3版本的ROCm套件导致的。据我所知，4.3版本的ROCm套件需要CentOs 7.9或8.3的支持 ![Screenshot_20220419_185631_com huawei browser](https://user-images.githubusercontent.com/86460876/163992505-1472e06a-6f02-48ab-82ac-333a21029342.jpg) 我们在更低版本的CentOS上用了4.0版本的ROCm套件。
> 
> 我本地环境使用的是Centos 7.6, Rocm是4.3，但是编译kokkos的报错了，可能我需要低版本的kokkos?

4.3版本的ROCm已通过Kokkos官方最新版本3.5.00的测试。但对于centos 7.6我们建议环境为：
cmake 3.20及以上
rocm 4.0.1或3.9.x
python3
g++ 8.x及以上（用于clang++调用）
